const jokes = [
  "Why do programmers prefer dark mode? Because light attracts bugs.",
  "Why do Java developers wear glasses? Because they can't C#.",
  "What’s a programmer’s favorite hangout place? The Foo Bar.",
  "Why do Python programmers have low self-esteem? Because they're constantly comparing their self to others.",
  "Why was the JavaScript developer sad? Because he didn’t know how to ‘null’ his feelings.",
  "Why did the programmer quit his job? Because he didn’t get arrays.",
  "Why do programmers hate nature? It has too many bugs.",
  "How do you comfort a JavaScript bug? You console it.",
  "Why did the developer go broke? Because he used up all his cache.",
  "What is a programmer's favorite musical key? C#.",
  "Why was the function feeling down? It didn’t get called.",
  "Why don’t bachelors like Git? Because they are afraid to commit.",
  "What do you call 8 hobbits? A hobbyte.",
  "Why did the array go to therapy? It had too many issues to sort out.",
  "What’s the object-oriented way to become wealthy? Inheritance.",
  "Why did the database administrator leave his wife? She had one-to-many relationships.",
  "Why do programmers prefer using the terminal? Because they hate windows.",
  "Why couldn’t the string become an integer? It couldn’t parse itself.",
  "Why did the boolean marry the integer? Because she couldn’t find a true love.",
  "Why did the bit go to school? To become a byte.",
  "How many programmers does it take to change a light bulb? None. That’s a hardware problem.",
  "Why do JavaScript devs hate reading? Because the 'readme' is never updated.",
  "What do you call a programmer from Finland? Nerdic.",
  "Why did the CSS developer go crazy? Because he couldn't contain his divs.",
  "Why did the programmer cross the road? To get to the next iteration.",
  "What do programmers do at lunchtime? They grab a byte.",
  "Why don’t programmers like to go outside? The sunlight causes too many glares.",
  "What do you call a programmer in a suit? The exception.",
  "Why did the JavaScript file break up with the HTML file? Because it had too many scripts.",
  "Why are assembly programmers always soaking wet? Because they work below C-level.",
  "Why don’t Java developers play hide and seek? Because they don’t want to be caught in a try block.",
  "What’s a programmer’s favorite movie? The Boolean Identity.",
  "Why did the loop break up with the array? It couldn’t iterate the relationship.",
  "What do you get when you cross a computer and a life guard? A screensaver.",
  "Why did the frontend developer stay home? Because he didn't want to face the backend.",
  "What do you call a loop that never ends? An infinite jest.",
  "Why did the debugger break up with the code? It couldn’t handle the exceptions.",
  "What does a programmer do after a breakup? Git commit and move on.",
  "Why do programmers make terrible musicians? Because they always play by ear and hate sharp notes.",
  "Why was the React developer stuck in traffic? Because he didn’t know how to navigate.",
  "Why did the Node.js developer get a promotion? Because he handled everything asynchronously.",
  "What did the code say to the user? You complete me.",
  "Why did the C++ developer get thrown out of school? For having too many classes.",
  "Why don’t programmers trust user input? Because users are unpredictable.",
  "Why are computers so smart? Because they listen to their motherboards.",
  "Why did the coder always carry a bottle of water? To hydrate his stacks.",
  "Why was the terminal blushing? Because it saw the command prompt naked.",
  "What do you call a Git repo full of errors? A commit-mess.",
  "Why are keyboards so good at singing? They have the right pitch.",
  "What’s a programmer’s favorite exercise? Running tests."
];


Btn=()=>{
    let rand=Math.floor(Math.random()*jokes.length);
    document.getElementById("text").innerText="\""+jokes[rand]+"\"";
}